import type { Metadata } from "next";
import { Montserrat, Roboto, Griffy, Geist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const montserrat = Montserrat({
  variable: "--montserrat-font",
  display: "swap",
});
const roboto = Roboto({
  variable: "--roboto-font",
  display: "swap",
});
const griffy = Griffy({
  variable: "--griffy-font",
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(montserrat.variable, roboto.variable, griffy.variable, "font-sans", geist.variable)}
    >
      <body
        className={`min-h-full flex flex-col bg-black ${montserrat.variable} ${roboto.variable} ${griffy.variable}`}
      >
        <div className="bg-wrapper">
          <Header />
          <main> {children}</main>
        </div>
      </body>
    </html>
  );
}
